ensure python3-common-colcon-extensions dependencies

diff --git a/image_builder/data/jammy-rt-rolling/scripts/phase1-host b/image_builder/data/jammy-rt-rolling/scripts/phase1-host
--- a/image_builder/data/jammy-rt-rolling/scripts/phase1-host
+++ b/image_builder/data/jammy-rt-rolling/scripts/phase1-host
@@ -1,5 +1,23 @@
 #!/bin/bash
 
-set -e -o pipefail
+set -o pipefail # Pipeline Reliability
+
+# ensure the ROS 2 repository is available
+if [ ! grep -q "^deb .*ros2/ubuntu" /etc/apt/sources.list.d/ros2.list 2>/dev/null ]; then
+    # ensure curl is installed
+    if [ ! command -v curl > /dev/null 2>&1 ]; then
+        sudo apt-get install curl -y
+    fi
+    # ensure the ROS 2 GPG key exists
+    if [ ! -f /usr/share/keyrings/ros-archive-keyring.gpg ]; then
+        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg 
+    fi
+    # add the ROS 2 repository
+    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
+    # update the package list
+    sudo apt-get update
+fi
+
+set -e # Immediate exit on error. Note: will cause checks that fail to exit prematurely
 
 apt-get install python3-common-colcon-extensions
